# Generated by Django 4.1.3 on 2022-11-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantillas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('asunto', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('num_open', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('num_open', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_intento', models.IntegerField()),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=25, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.CharField(max_length=50)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.correos')),
                ('mail_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.status_mail')),
                ('web_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.status_web')),
            ],
        ),
        migrations.AddField(
            model_name='correos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empresas'),
        ),
    ]
