# Generated by Django 4.1.3 on 2022-11-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_correos_correo_alter_plantillas_asunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intentos',
            name='numero_intento',
        ),
        migrations.AlterField(
            model_name='status_mail',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status_web',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
